formatter: markdown
header-from: .header.md
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 3
  required: true
  sensitive: true
  type: true
  lockfile: false

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: replace
  template: |-
    [//]: # (BEGIN_TF_DOCS)

    {{ .Content }}

    [//]: # (END_TF_DOCS)
