apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-team-riker
spec:
  amiFamily: Bottlerocket
  instanceProfile: ${eks-cluster-id}-${eks-cluster-id}-initial-nodes
  subnetSelector:
    kubernetes.io/cluster/${eks-cluster-id}: "*"
    kubernetes.io/role/internal-elb: "1"
  securityGroupSelector:
    aws:eks:cluster-name: ${eks-cluster-id}
  tags:
    karpenter.sh/cluster_name: ${eks-cluster-id}
    karpenter.sh/provisioner: team-riker
    used_by: team-riker
    Name: team-riker-${eks-cluster-id}-karpenter
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: team-riker
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: NotIn
      values:
        - a1
        - c1
        - c3
        - inf1
        - t3
        - t2
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
        - "33"
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand", "spot"]
  providerRef:
    name: karpenter-team-riker
    tags:
      karpenter.sh/cluster_name: ${eks-cluster-id}
      karpenter.sh/provisioner: team-riker
  ttlSecondsAfterEmpty: 60
  limits:
    resources:
      cpu: "200"
  labels:
    billing-team: team-riker
    team: team-riker
    type: karpenter
  taints:
    - key: karpenter
      value: "true"
      effect: NoSchedule
    - key: billing-team
      value: "team-riker"
      effect: NoSchedule
